server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA: todo lo que no sea archivo va a index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy: /api/* → rednorte-bff:8080/api/*
    location /api/ {
        proxy_pass http://rednorte-bff:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
